name: Deploy Infra (Full Sync)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- STEP 1: CLEANUP ---
      - name: Cleanup before deploy
        run: |
          rm -rf .git
          rm -rf .github
          rm -rf venv
          rm -rf __pycache__
          rm -f .env

      # --- STEP 2: COPY ---
      - name: Copy project files via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: ${{ secrets.HETZNER_USER }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          source: "."
          target: "/home/vandl/infra"
          rm: true
          strip_components: 0

      # --- STEP 3: DEPLOY ---
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: ${{ secrets.HETZNER_USER }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          envs: DB_USER,DB_PASSWORD,DB_NAME,PGADMIN_EMAIL,PGADMIN_PASSWORD
          script: |
            cd /home/vandl/infra
            
            echo "POSTGRES_USER=clearway" > .env
            echo "POSTGRES_PASSWORD=$DB_PASSWORD" >> .env
            echo "POSTGRES_DB=clearway_db" >> .env
            
            echo "PGADMIN_DEFAULT_EMAIL=$PGADMIN_EMAIL" >> .env
            echo "PGADMIN_DEFAULT_PASSWORD=$PGADMIN_PASSWORD" >> .env
            
            docker compose -f docker-compose.prod.yml up -d --build --remove-orphans
        env:
          DB_USER: clearway
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: clearway_db
          PGADMIN_EMAIL: ${{ secrets.PGADMIN_EMAIL }}
          PGADMIN_PASSWORD: ${{ secrets.PGADMIN_PASSWORD }}